### ISSUE TITLE
Grabar discos 

### ISSUE THREAD

**Issue by Carmeng08** [Pindulfo/Projecto-1#12]
Grabar discos del proyecto 
**5º Tarea**

**Comment by Pindulfo** [comment]
Buenas tardes, he terminado de grabar el disco del primer capítulo sobre el tema

**Comment by Carmeng08** [comment]
Vale,yo termino esta tarde de grabar el disco correspondiente al 2º capítulo

**Comment by MarioBenP** [comment]
Me he decido a grabar, la secuencia de como solucione el bug del resumen meteorológico. 
Esta noche lo tenemos todo, verdad?

**Comment by Carmeng08** [comment]
Buenos días de nuevo,  todo grabado

**Comment by ivanvallejoo** [comment]
Buenas tardes, se me había olvidado añadir una información en el tercer capítulo. Ahora sí todo terminado
